
services:
  qufit-backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-whgustn730/qufit-backend}:${DOCKER_TAG:-latest}
    container_name: qufit-backend
    ports:
      - "8080:8080"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/logs:/app/logs
    depends_on:
      - redis

  qufit-frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-whgustn730/qufit-frontend}:${DOCKER_TAG:-latest}
    container_name: qufit-frontend
    ports:
      - "3000:80" #80번 포트를 3000번으로 매핑 -> 클라이언트에서 3000번 포트로 들어오면 Nginx 80 포트 매핑
    env_file:
      - ./front-end/.env
#    volumes:
#      - ./front-end/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qufit-backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  logs:
  redis_data: