version: '3'

services:
  qufit-backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE:-whgustn730/qufit}:${DOCKER_TAG:-latest}
    container_name: qufit-backend
    ports:
      - "8080:8080"
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  logs:
  redis_data: