version: '3'

services:
  qufit:
    build:
      context: .
      dockerfile: Dockerfile
    image: whgustn730/qufit:latest  # DockerHub에 푸시할 이미지
    container_name: qufit-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # 로그 파일을 호스트와 공유
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
  logs:
  redis_data: